server:
  port: 8100 
spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://recofit-db.caxwmkvaba6j.ap-northeast-2.rds.amazonaws.com/registration
    username: root
    password: 2!qkfzlfldk;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      
  kafka:
    producer:
      bootstrap-servers: ec2-3-39-234-99.ap-northeast-2.compute.amazonaws.com:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer #      org.apache.kafka.common.serialization.StringSerializer